<a href="https://colab.research.google.com/github/kavindiarunika/Deep-Learning/blob/main/indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [2]:
x=torch.arange(1,10).reshape(1,3,3)

In [3]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [4]:
x.shape

torch.Size([1, 3, 3])

In [5]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
#let index in middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [7]:
x[0][0][0]

tensor(1)

In [8]:
#use :to select "all" of target dim
x[:,0]

tensor([[1, 2, 3]])

In [9]:
x[:,:,1]

tensor([[2, 5, 8]])

In [10]:
x[:,1,1]

tensor([5])

In [11]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [13]:
#change the valie of array
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [14]:
tensor =torch.ones(7)
numpy_tensor =tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))