In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.6.0+cpu


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector =torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
Matrix=torch.tensor([[2,3],
                     [4,5],
                     [6,7]])
Matrix

tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [ ]:
#tensor
Tensor=torch.tensor([[[1,1],[2,3]]])
Tensor


tensor([[[1, 1],
         [2, 3]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.size()

torch.Size([1, 2, 2])

## **Random tensors**

In [ ]:
#create a random tensor
random_tensor =torch.rand(3,4)
random_tensor

tensor([[0.1708, 0.6186, 0.1674, 0.2926],
        [0.0031, 0.2743, 0.2020, 0.3141],
        [0.3476, 0.5012, 0.7905, 0.8022]])

In [ ]:
image_tensor =torch.rand(size=(3,224,224))
image_tensor.shape

torch.Size([3, 224, 224])

In [ ]:
#create a tensor for all zeros
zeros =torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten =torch.arange(start=1 ,end=11 ,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
float_32 = torch.tensor([3,4,5,6])

In [ ]:
float_32.dtype

torch.int64

In [ ]:
float_16 = float_32.type(torch.float16)

In [ ]:
float_16.dtype

torch.float16

In [ ]:
tensor =torch.tensor([1,2,3,4])
tensor +10

tensor([11, 12, 13, 14])

In [ ]:
print (tensor ,"*", tensor)

tensor([1, 2, 3, 4]) * tensor([1, 2, 3, 4])


In [ ]:
print(f"equals:{tensor * tensor}")

equals:tensor([ 1,  4,  9, 16])


In [ ]:
torch.matmul(tensor,tensor)

tensor(30)

In [ ]:
value =0
for i in range (len(tensor)):
  value += tensor[i] *tensor[i]
  print(value)

tensor(1)
tensor(5)
tensor(14)
tensor(30)


In [ ]:
tensor @ tensor

tensor(30)

In [ ]:
x= torch.arange(0,100,10)
x,x.dtype



(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.max(x),min(x)

(tensor(90), tensor(0))

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x= torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
resize = x.reshape(1,9)

In [ ]:
resize

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_stack=torch.stack([x,x,x,x] ,dim=0)
x_stack

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

**indexing(selecting data from pytorch)**

In [ ]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B =torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.3503, 0.5483, 0.9115, 0.8312],
        [0.4795, 0.2039, 0.0600, 0.1427],
        [0.3226, 0.5614, 0.1753, 0.9120]])
tensor([[0.7252, 0.3699, 0.6035, 0.6157],
        [0.1565, 0.7730, 0.5952, 0.0979],
        [0.6033, 0.1553, 0.7446, 0.3820]])


In [ ]:
random_seed=42
torch.manual_seed(random_seed)

random_tensor_C=torch.rand(1,4)
torch.manual_seed(random_seed)
random_tensor_D=torch.rand(1,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593]])
tensor([[True, True, True, True]])


In [ ]:
import torch
torch.cuda.is_available()

False