<a href="https://colab.research.google.com/github/kavindiarunika/Deep-Learning/blob/main/matrix2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [3]:
x_reshaped = x.reshape(9,1)

In [4]:
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [5]:
#change the view
z=x.view(1,9)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [6]:
x_stack = torch.stack([x,x,x,x],dim=1)
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [9]:
X_SQUEEZED =x_reshaped.squeeze(dim=0)
X_SQUEEZED

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [10]:
#UNSQUEEZED
X_UNSQUEZZED = X_SQUEEZED.unsqueeze(dim=0)

In [11]:
X_UNSQUEZZED

tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [16]:
x_orginal = torch.rand(size=(224,224,3))
x_orginal

tensor([[[0.6490, 0.4198, 0.8509],
         [0.4581, 0.4086, 0.6790],
         [0.6227, 0.0492, 0.5334],
         ...,
         [0.4212, 0.7827, 0.5094],
         [0.7171, 0.9617, 0.0836],
         [0.2319, 0.2613, 0.3357]],

        [[0.9398, 0.7505, 0.9614],
         [0.2779, 0.6978, 0.1496],
         [0.9128, 0.7160, 0.5821],
         ...,
         [0.7798, 0.7557, 0.4114],
         [0.5270, 0.8772, 0.1015],
         [0.2143, 0.3363, 0.8604]],

        [[0.9604, 0.6221, 0.7542],
         [0.7616, 0.1261, 0.5750],
         [0.0625, 0.8300, 0.9599],
         ...,
         [0.9870, 0.5949, 0.4621],
         [0.9022, 0.1223, 0.9132],
         [0.9014, 0.6375, 0.8881]],

        ...,

        [[0.6122, 0.3103, 0.3745],
         [0.4288, 0.8665, 0.6548],
         [0.8271, 0.4082, 0.6308],
         ...,
         [0.1084, 0.7503, 0.5471],
         [0.1339, 0.4356, 0.4944],
         [0.3777, 0.9660, 0.9710]],

        [[0.2165, 0.0415, 0.5815],
         [0.5245, 0.8581, 0.6100],
         [0.

In [17]:
#permutethe orginal temsor
x_permuted = x_orginal.permute(2,0,1)
x_permuted

tensor([[[0.6490, 0.4581, 0.6227,  ..., 0.4212, 0.7171, 0.2319],
         [0.9398, 0.2779, 0.9128,  ..., 0.7798, 0.5270, 0.2143],
         [0.9604, 0.7616, 0.0625,  ..., 0.9870, 0.9022, 0.9014],
         ...,
         [0.6122, 0.4288, 0.8271,  ..., 0.1084, 0.1339, 0.3777],
         [0.2165, 0.5245, 0.8070,  ..., 0.8107, 0.7246, 0.8187],
         [0.9014, 0.9002, 0.8195,  ..., 0.4610, 0.0087, 0.9653]],

        [[0.4198, 0.4086, 0.0492,  ..., 0.7827, 0.9617, 0.2613],
         [0.7505, 0.6978, 0.7160,  ..., 0.7557, 0.8772, 0.3363],
         [0.6221, 0.1261, 0.8300,  ..., 0.5949, 0.1223, 0.6375],
         ...,
         [0.3103, 0.8665, 0.4082,  ..., 0.7503, 0.4356, 0.9660],
         [0.0415, 0.8581, 0.6069,  ..., 0.7032, 0.3244, 0.6512],
         [0.6056, 0.4151, 0.5345,  ..., 0.3861, 0.2913, 0.9816]],

        [[0.8509, 0.6790, 0.5334,  ..., 0.5094, 0.0836, 0.3357],
         [0.9614, 0.1496, 0.5821,  ..., 0.4114, 0.1015, 0.8604],
         [0.7542, 0.5750, 0.9599,  ..., 0.4621, 0.9132, 0.

## indexing