<a href="https://colab.research.google.com/github/kavindiarunika/Deep-Learning/blob/main/reproducbility.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# try to take randome out of number

In [3]:
tensor_A=torch.rand(3,3)
tensor_B=torch.rand(3,3)

In [4]:
print(tensor_A)
print(tensor_B)

tensor([[0.6526, 0.3815, 0.0011],
        [0.7678, 0.0163, 0.8447],
        [0.9827, 0.9294, 0.9603]])
tensor([[0.2892, 0.5137, 0.7037],
        [0.7252, 0.1271, 0.0785],
        [0.1566, 0.6689, 0.4886]])


In [5]:
print(tensor_B == tensor_A)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [6]:
import torch

In [7]:
random_seed = 42
torch.manual_seed(random_seed)

random_tensor_c = torch.rand(3,3)
torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,3)
print(random_tensor_c)
print(random_tensor_D)
print(random_tensor_D == random_tensor_c)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### extra resource for reproducbility